from enum import Enum


class FraudSignal(str, Enum):
    HIGH_AMOUNT = "HIGH_AMOUNT"

    SUSPICIOUS_DEVICE = "SUSPICIOUS_DEVICE"

    LOCAL_IP = "LOCAL_IP"

    HIGH_TRANSACTION_COUNT = "HIGH_TRANSACTION_COUNT"

    HIGH_TRANSACTION_VOLUME = "HIGH_TRANSACTION_VOLUME"

    BLACKLISTED_DEVICE = "BLACKLISTED_DEVICE"

    BLACKLISTED_IP = "BLACKLISTED_IP"

    HIGH_VELOCITY = "HIGH_VELOCITY"
