from enum import Enum


class NotificationType(
    str,
    Enum,
):
    TRANSACTION_REVIEW = "TRANSACTION_REVIEW"

    TRANSACTION_REJECTED = "TRANSACTION_REJECTED"

    BLACKLIST_TRIGGERED = "BLACKLIST_TRIGGERED"

    HIGH_RISK_TRANSACTION = "HIGH_RISK_TRANSACTION"

    USER_BLOCKED = "USER_BLOCKED"
