from enum import Enum


class NotificationSeverity(
    str,
    Enum,
):
    INFO = "INFO"
    SUCCESS = "SUCCESS"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class NotificationType(
    str,
    Enum,
):
    TRANSACTION_REVIEW = "TRANSACTION_REVIEW"
    TRANSACTION_REJECTED = "TRANSACTION_REJECTED"
    TRANSACTION_STATUS_UPDATED = "TRANSACTION_STATUS_UPDATED"
    BLACKLIST_TRIGGERED = "BLACKLIST_TRIGGERED"
    HIGH_RISK_TRANSACTION = "HIGH_RISK_TRANSACTION"
    SECURITY_ALERT = "SECURITY_ALERT"
    USER_BLOCKED = "USER_BLOCKED"
