from enum import Enum


class AuditAction(
    str,
    Enum,
):
    LOGIN_SUCCESS = "LOGIN_SUCCESS"

    LOGIN_FAILED = "LOGIN_FAILED"

    LOGIN_BLOCKED = "LOGIN_BLOCKED"

    REFRESH_TOKEN = "REFRESH_TOKEN"

    TRANSACTION_CREATED = "TRANSACTION_CREATED"

    TRANSACTION_REVIEWED = "TRANSACTION_REVIEWED"

    TRANSACTION_APPROVED = "TRANSACTION_APPROVED"

    TRANSACTION_REJECTED = "TRANSACTION_REJECTED"
